question_data = [
{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                  "question": "A Saxophone is a brass instrument.", "correct_answer": "False",
                                  "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "History",
                                  "question": "Martin Luther King Jr. and Anne Frank were born the same year. ",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                                  "question": "In Half-Life 2, if you play the zombies&#039; speech in reverse, they actually speak coherent English.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                                  "question": "Tony Hawk&#039;s Pro Skater was released in 1999.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                  "question": "The Sonoran Desert is located in eastern Africa.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                                  "question": "Donkey Kong was originally set to be a Popeye arcade game.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                                  "question": "The first &quot;Metal Gear&quot; game was released for the PlayStation 1.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
                                  "question": "The &quot;Berenstein Bears&quot; is the correct spelling of the educational children&#039;s book series&#039; name.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                                  "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "History",
                                  "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                  "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                  "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Mythology",
                                  "question": "According to Greek Mythology, Zeus can control lightning.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                                  "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                                  "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
                                  "question": "This is the correct spelling of &quot;Supercalifragilisticexpialidocious&quot;.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                                  "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness Vest&quot;",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium",
                                  "category": "Entertainment: Cartoon &amp; Animations",
                                  "question": "Donald Duck played the role of Bob Cratchit in Disney&#039;s 1983 adaptation of A Christmas Carol.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Science: Mathematics",
                                  "question": "A universal set, or a set that contains all sets, exists.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                                  "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                  "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                                  "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
                                  "question": "Metallica collaborated with Rowan Atkinson&#039;s Mr Bean on a 1992 comic relief single.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Geography",
                                  "question": "Only one country in the world starts with the letter Q.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
                                  "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                                  "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
                                  "question": "In &quot;Star Trek&quot;, Klingons are commonly referred to as &quot;Black Elves&quot;.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
                                  "question": "&quot;The Simpsons&quot; family is named after creator Matt Groening&#039;s real family.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
                                  "question": "You can square root a negative number with an imaginary number &quot;i&quot;.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "History",
                                  "question": "Japan was part of the Allied Powers during World War I.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                                  "question": "Linux was first created as an alternative to Windows XP.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                                  "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                                  "question": "There are 2 player roles in Trouble in Terrorist Town.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                                  "question": "When BMW was established in 1916, it was producing automobiles.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
                                  "question": "The book 1984 was published in 1949.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                  "question": "The Great Wall of China is visible from the moon.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                  "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
                                  "question": "The Xenomorph from the science fiction film &quot;Alien&quot; has acidic blood.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Film",
                                  "question": "The weapon Clint Eastwood uses in &quot;Dirty Harry&quot; was a .44 Automag.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "History",
                                  "question": "Adolf Hitler was tried at the Nuremberg trials.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Science: Gadgets",
                                  "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                  "question": "AMD created the first consumer 64-bit processor.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                                  "question": "The Paradox Interactive game &quot;Stellaris&quot; was released in 2016.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                  "question": "John Williams composed the music for &quot;Star Wars&quot;.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                  "question": "Daft Punk originated in France.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                                  "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
                                  "question": "&quot;Number 16 Bus Shelter&quot; was a child&#039;s name that was approved by the New Zealand government.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                                  "question": "In &quot;Portal 2&quot;, Cave Johnson started out Aperture Science as a shower curtain company.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                                  "question": "The pickled gherkin was first added to hamburgers because a US health law required all fast-food to include a source of Vitamin C.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                                  "question": "Furby was released in 1998.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Politics",
                                  "question": "Joko Widodo has appeared in the cover of a TIME magazine.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "History",
                                  "question": "Kublai Khan is the grandchild of Genghis Khan?",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                  "question": "Pluto is a planet.", "correct_answer": "False",
                                  "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "History",
                                  "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "History",
                                  "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy",
                                  "category": "Entertainment: Japanese Anime &amp; Manga",
                                  "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                  "question": "You could walk from Norway to North Korea while only passing through Russia.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                                  "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man&#039;s Tree.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                                  "question": "In the game &quot;Melty Blood Actress Again Current Code&quot;, you can enter Blood Heat mode in Half Moon style.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]}

]
